name = "bigsolo-functions"
compatibility_date = "2025-09-14"
pages_build_output_dir = "." # Indique à Wrangler que c'est un projet Pages et où se trouvent les fichiers statiques (à la racine).


[[kv_namespaces]]
binding = "IMG_CHEST_CACHE"
id = "24632818ff5d495e8ec68eb26dd49136"

[[kv_namespaces]]
binding = "INTERACTIONS_LOG"
id = "9bd6247311a141c58512bffb5e133311"

[[kv_namespaces]]
binding = "INTERACTIONS_CACHE"
id = "0653d72f16bb45adb5155e2ea69e5031"

[pages_functions]
[[pages_functions.bindings]]
# Le cron s'exécute toutes les 5 minutes.
cron = "*/30 * * * *"
# La fonction à exécuter est celle qui se trouve dans le fichier /functions/api/process-log.js
functions = ["/functions/api/process-log.js"]